name: twilio_flutter
description: A Package that helps with twilio API.Supports Twilio Programmable SMS.
version: 0.0.9
homepage: https://github.com/adarshbalu/twilio_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
